### ISSUE TITLE
How is the development coming?

### ISSUE THREAD

**Issue by 0xMeir** [clocked0ne/passport-outlook#1]
Hello, I somehow missed this on npm and I went ahead and modified the passport-windowslive strategy to support outlook https://github.com/globlee/passport-outlook

What particularly is not working with this package? Whatever is the matter, I would recommend this website: https://oauthplay.azurewebsites.net/ or if you want to just copy some code from my repository.

**Comment by clocked0ne** [comment]
Hi @globlee I think you published your module shortly after the company I'm working at put our Outlook integration plans on hold, but we are now back on the case.

This module is now working as of v1 released today, I've restructured it somewhat from the package you published so now there is a working test suite, your feedback would be welcome.
