### ISSUE TITLE
TokenError: Malformed auth code.

### ISSUE THREAD

**Issue by JEngdahl** [clocked0ne/passport-outlook#10]
Hello, I'm attempting to use passport-outlook to authenticate a user. 

I seem to have all of the steps complete as I can get through the auth flow no problem, but when the request hits the callback-url I receive the TokenError: Malformed auth code. error

I've done some extensive searching but haven't found anything to go on. 

Thank you,
  Jarett

`TokenError: Malformed auth code.
    at Strategy.OAuth2Strategy.parseErrorResponse (/app/node_modules/passport-oauth2/lib/strategy.js:329:12)
    at Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:376:16)
    at /app/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /app/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/app/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by JEngdahl** [comment]
Logging the error at 
>/app/node_modules/passport-oauth2/lib/strategy.js:376:16

I get the following : 

{ error: 'invalid_grant',
  error_description: 'Malformed auth code.' }

**Comment by JEngdahl** [comment]
@clocked0ne

**Comment by clocked0ne** [comment]
I've not seen this kind of error before as far as I can remember. Have you used `offline_access` scope to ensure you get a refresh token back? My understanding is that this response suggests an invalid/missing token parts.

Can you provide an example of the code you're using with any non-essential code and credentials removed/hidden?

**Comment by JEngdahl** [comment]
`
passport.use(new OutlookStrategy({
    clientID: secrets.OUTLOOK_API_ID,
    clientSecret: secrets.OUTLOOK_API_PASSWORD,
    callbackURL: secrets.OUTLOOK_CALLBACK_URL
  },
  function(accessToken, refreshToken, profile, done) {
    console.log(accessToken);
    console.log(refreshToken);
    console.log(profile);

  }
));

router.get('/api/auth/login/outlook',
  passport.authenticate('windowslive', {
    scope: [
      'openid',
      'profile',
      'offline_access',
      'https://outlook.office.com/Mail.ReadWrite',
      'https://outlook.office.com/Mail.Send',
      'https://outlook.office.com/Calendars.ReadWrite'
    ]
  })
);


router.get('/api/auth/callback/outlook',
  passport.authenticate('windowslive', { failureRedirect: '/login' }),
  function(req, res) {
    // Successful authentication, redirect home.
    res.redirect('/');
})`

**Comment by JEngdahl** [comment]
@clocked0ne here is a snippet with the passport init, scopes,  as well as the callback URL
In my project, I am using multiple authentication methods (Google + Outlook) do you think that that has anything to do with it?

**Comment by JEngdahl** [comment]
Fixed: Issue was with my outlook account. I think that since I created it to test with it had not been processed by Microsoft yet / or it was that scopes are case sensitive.

@clocked0ne Thank you and sorry!
