### ISSUE TITLE
 'invalid_request: The provided value for the input parameter 'redirect_uri' is not valid.' 

### ISSUE THREAD

**Issue by miaIra90** [clocked0ne/passport-outlook#14]
I've tried to connect outlook registration to my web app..I've tried all endpoints, but it still has issue 'invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.' Localhost works fine, problem only with remote server.

https://{domain_name}/auth/outlook/login/callback

https://{domain_name}/auth

https://{domain_name}/auth/outlook

https://{domain_name}/auth/outlook/login

https://{domain_name}/V1/auth/outlook/login/callback

https://{domain_name}/V1/auth

https://{domain_name}/V1/auth/outlook

https://{domain_name}/V1/auth/outlook/login

**Comment by clocked0ne** [comment]
Hi @IrinaMironova

Unfortunately it is very hard to say the exact problem without knowing your configuration in the https://apps.dev.microsoft.com/ Application Registration Portal.

Please check that the URLs configured against your Application for redirection match those listed by you above, including whether or not they are using HTTP/HTTPS. As this is an issue I have not received before I expect that these settings are the problem.

Let me know if I can be of any further help once you have checked this.

**Comment by miaIra90** [comment]
Is it necessarily to include 'www' to domain_name?

**Comment by clocked0ne** [comment]
Yes it most likely would be, if in doubt I believe you can register both www and non-www domains URLs for the callbacks, as many as needed.
