### ISSUE TITLE
Not able to choose account

### ISSUE THREAD

**Issue by jensjeriksson** [clocked0ne/passport-outlook#17]
prompt=select_account is not getting added to the login link. This results in users bot being able to choose wich account to login with.
Any suggenstions on how to fix it?

**Comment by clocked0ne** [comment]
You should add the prompt value as one of the options when configuring the strategy, e.g:

```js
new OutlookStrategy({
  clientID: OUTLOOK_CLIENT_ID,
  clientSecret: OUTLOOK_CLIENT_SECRET,
  callbackURL: 'http://www.example.com/auth/outlook/callback',
  prompt: 'select_account'
}
```

**Comment by jensjeriksson** [comment]
I have tried that and it still does not work with windowslive.
With GoogleStrategy it worked immediately, If I copy the link and add the prompt=select_account manually it works fine, but passport seems to leave it out in this package

**Comment by clocked0ne** [comment]
Apologies, my mistake, I thought the options were passed through but it seems I need to add this to `authorizationParams`.

I will push a new version to fix this, if you want to try this locally you should be able to simply insert into this file at this line:
https://github.com/clocked0ne/passport-outlook/blob/413203e7223a7a1fd257105dd137b7a517403dbf/lib/strategy.js#L104
```js
if (options.prompt) {
  params['prompt'] = options.prompt;
}
```
That should be enough for you.

**Comment by jensjeriksson** [comment]
Thanks mate!
