### ISSUE TITLE
Unable to fetch tokens and user profile info auth flow error

### ISSUE THREAD

**Issue by azeem91** [clocked0ne/passport-outlook#2]
Hello, I'm trying to fetch user profile and tokens.
**"Strategy.prototype.userProfile"** this function is **not working** properly. On removing this function Oath process completes without any error and returns accessToken in **done** function.
I have tried with the example given in package. _**I just want to use it for Outlook app**_ .

Note : I have an Outlook app only not windows live account.
kindly fix it or share some solution.

Thanks

**Comment by clocked0ne** [comment]
Hi @azeem91 this package has been modified and is working correctly with the Outlook API REST endpoints now, you should find you do not experience any issues now.
